apiVersion: v1
kind: PersistentVolume # Create a PV
metadata:
  name: mariadb-data-db-stg # Sets PV's name
  namespace: jasperreport-server-stg
  labels:
    type: local # Sets PV's type to local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi # Sets PV Volume
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/mariadb-ammar" # Sets the volume's path
---
apiVersion: v1
kind: PersistentVolumeClaim # Create PVC
metadata:
  name: mariadb-data-db-stg-claim # Sets name of PV
  namespace: jasperreport-server-stg
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce # Sets read and write access
  resources:
    requests:
      storage: 10Gi # Sets volume size