name: Production Deployment

on:
  pull_request:
    types:
      - closed
    branches:
      - production
jobs:
  if-merged:
    name: Merge Success
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The Staging PR was merged into Production

  deploy-production:
    name: Deploy Production
    needs: if-merged
    runs-on: self-hosted
    environment:
      name: Production
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: production
          fetch-depth: 0

      - name: Get Version
        uses: tw3lveparsecs/github-actions-setvars@latest
        with:
          envFilePath: ./helm/version.env

      - name: ArgoCD Deploy to Production
        run: |
          argocd login --insecure  ${{ secrets.ARGOCD_SERVER }} --username  ${{ secrets.ARGOCD_USER }} --password  ${{ secrets.ARGOCD_PASS}}
          argocd app create jasperreports-prd --repo https://github.com/ammarun11/k8s-jasperreport-lab.git --path helm/jasperreports --values values-prd.yaml --revision ${{ steps.get-version.outputs.VERSION }} --dest-namespace jasperreports-server-prd --dest-server https://kubernetes.default.svc --upsert
          argocd --grpc-web app sync jasperreports-prd --force
          argocd --grpc-web app wait jasperreports-prd --timeout 300
          
      - name: Telegram Notification
        if: cancelled() == false
        uses: xinthink/action-telegram@v1.1
        with:
          botToken: ${{ secrets.TELE_BOT_TOKEN }}
          chatId: ${{ secrets.TELE_CHAT_ID }}
          jobStatus: ${{ job.status }}
          skipSuccess: false
